### ISSUE TITLE
An issue on multiprocessing with CUDA

### ISSUE THREAD

**Issue by kmbmjn** [jhfjhfj1/autokeras#106]
The example code on MNIST showed an issue on multiprocessing with CUDA.
I guess CUDA doesn't work well with the multiprocessing https://pytorch.org/docs/stable/notes/windows.html
I use Windows10, Python 3.6.5, CUDA 9.0, and tensorflow-gpu==1.8.0. I followed requirements.txt to install others.
Using commands "torch.version.cuda" and "torch.cuda.is_available()", I also checked CUDA 9.0 works well on my environment.

...........................................
Epoch 1: loss 1.8169708251953125, metric_value 0.987
...........................................
Epoch 2: loss 1.694014310836792, metric_value 0.9866
...........................................
Epoch 3: loss 1.5495505332946777, metric_value 0.9884
...........................................
Epoch 4: loss 1.7369670867919922, metric_value 0.9882
...........................................
Epoch 5: loss 2.2431726455688477, metric_value 0.9842
...........................................
Epoch 6: loss 1.821488618850708, metric_value 0.9864
...........................................
Epoch 7: loss 1.3172129392623901, metric_value 0.9908
...........................................
Epoch 8: loss 1.3580961227416992, metric_value 0.9906
...........................................
Epoch 9: loss 1.2147481441497803, metric_value 0.992
...........................................
Epoch 10: loss 1.3565152883529663, metric_value 0.9916
...........................................
Epoch 11: loss 1.201681137084961, metric_value 0.9916
...........................................
Epoch 12: loss 1.9307321310043335, metric_value 0.987
...........................................
Epoch 13: loss 1.2660953998565674, metric_value 0.993
...........................................
Epoch 14: loss 1.2389497756958008, metric_value 0.9924
...........................................
Epoch 15: loss 1.3451954126358032, metric_value 0.992
...........................................
Epoch 16: loss 2.506535291671753, metric_value 0.9844
...........................................
Epoch 17: loss 2.018087387084961, metric_value 0.989
...........................................
Epoch 18: loss 1.1533660888671875, metric_value 0.9934
...........................................
Epoch 19: loss 1.493323802947998, metric_value 0.9908
No loss decrease after 5 epochs
THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1533090623466\work\torch\csrc\generic\StorageSharing.cpp line=231 error=63 : OS call failed or operation not supported on this OS
Traceback (most recent call last):
  File "ak_mnist.py", line 10, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "C:\Users\kmbmjn\Anaconda3\lib\site-packages\autokeras\image_supervised.py", line 238, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "C:\Users\kmbmjn\Anaconda3\lib\site-packages\autokeras\image_supervised.py", line 41, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "C:\Users\kmbmjn\Anaconda3\lib\site-packages\autokeras\search.py", line 189, in search
    metric_value, loss, graph = train_results.get(timeout=remaining_time)[0]
  File "C:\Users\kmbmjn\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[(0.9899199999999999, tensor(1.7033, device='cuda:0'), <autokeras.graph.Graph object at 0x00000174DB1BC7B8>)]'. Reason: 'RuntimeError('cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\\programdata\\miniconda3\\conda-bld\\pytorch_1533090623466\\work\\torch\\csrc\\generic\\StorageSharing.cpp:231',)'

**Comment by eagleoflqj** [comment]
Same error.
My solution:
remove
```python
pool = multiprocessing.Pool(1)
```
and
```python
finally:
        # terminate and join the subprocess to prevent any resource leak
        pool.terminate()
        pool.join()
```
then change
```python
train_results = pool.map_async(train, [(graph, train_data, test_data, self.trainer_args,
                                                 os.path.join(self.path, str(model_id) + '.png'),
                                                 self.metric, self.loss, self.verbose)])
```
to
```python
train_results = list(map(train, [(graph, train_data, test_data, self.trainer_args,
                                                os.path.join(self.path, str(model_id) + '.png'),
                                                self.metric, self.loss, self.verbose)]))
```
and
```python
metric_value, loss, graph = train_results.get(timeout=remaining_time)[0]
```
to
```python
metric_value, loss, graph = train_results[0]
```

**Comment by eagleoflqj** [comment]
Well I just saw issues76, aa18514's method seems better, since there is only one item in the list.

**Comment by xialulu826** [comment]
when I run mnist ,I can not get the data.
"C:\Program Files\Python36\python.exe" D:/devkit_tracking/autokeras-0.2.1/examples/mnist.py
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Program Files\Python36\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Program Files\Python36\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Program Files\Python36\lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Program Files\Python36\lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python36\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\data_utils.py", line 222, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Program Files\Python36\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] >

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/devkit_tracking/autokeras-0.2.1/examples/mnist.py", line 5, in <module>
    (x_train, y_train), (x_test, y_test) = mnist.load_data()
  File "C:\Program Files\Python36\lib\site-packages\keras\datasets\mnist.py", line 23, in load_data
    file_hash='8a61469f7ea1b51cbae51d4f78837e45')
  File "C:\Program Files\Python36\lib\site-packages\keras\utils\data_utils.py", line 224, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://s3.amazonaws.com/img-datasets/mnist.npz: None -- [WinError 10054]。

Process finished with exit code 1

**Comment by kmbmjn** [comment]
I could conducted some experiments after applying eagleoflqj's comment. I think it solved my problem. Thanks!

**Comment by xialulu826** [comment]
@eagleoflqj  Thanks for your solution,it works.

**Comment by jhfjhfj1** [comment]
Thank you @eagleoflqj !
We have changed the multiprocessing to torch.multiprocessing.
@kmbmjn @xialulu826 Would you like to try again with our latest release to see if it works?

**Comment by eagleoflqj** [comment]
It works! @jhfjhfj1
