### ISSUE TITLE
doens't run on multi gpu system when only allocating 1 device

### ISSUE THREAD

**Issue by JaspervDalen** [jhfjhfj1/autokeras#315]
### Bug Description
AutoKeras won't work on a multi gpu machine when only allocating one gpu. It just freezes. Allocating two makes it work but it uses only one. I also get a lot of memory errors when trying to make it generate a model. around the 10th model.

### Reproducing Steps
  * Step 1: have a multi gpu machine
  * Step 2: use os.environ['CUDA_VISIBLE_DEVICES'] = "1" to select the 2nd gpu (any number will (not) work)
 * Step 3: use the mnist example
* Step 4: wait until you spend to much time and cancel

### Expected Behavior
not freeze and use gpu/cpu. At the moment it just runs but I can't see usage of cpu or gpu.

### Setup Details
Include the details about the versions of:
 - OS type and version: mac os mojave version 10.14
 - Python: 3.6
 - autokeras: master
 - keras: 2.2
 - tensorflow:1.10
- running on a GeForce GTX 1080

**Comment by tl-yang** [comment]
Hi @JaspervDalen , thank you for the bug report. Could you please specify the version of autokeras?

**Comment by JaspervDalen** [comment]
I pulled and installed this repo 2 days ago. So bleeding edge? I am at the moment unable to check the exact version as this is installed at work.

**Comment by hemangjoshi37a** [comment]
Have you found any solution??

**Comment by jhfjhfj1** [comment]
@tl-yang I think this issue is solved. If so, please close the issue. Thanks.

**Comment by jhfjhfj1** [comment]
I believe this is solved. If you still have this bug, please reopen this issue. Thanks.
